'use strict';

const CONFIG = {
    STORE_KEY: 'osiris_db_v3',
    BACKUP_KEY: 'osiris_db_v3_backup',
    SCHEMA_VERSION: 3,
    PURGATORY_THRESHOLD: 3,
    MONTHS: ['GENNAIO','FEBBRAIO','MARZO','APRILE','MAGGIO','GIUGNO','LUGLIO','AGOSTO','SETTEMBRE','OTTOBRE','NOVEMBRE','DICEMBRE'],
    DOW: ['L','M','M','G','V','S','D']
};

const GRADES = [
    { grade: 'GRADO 0', tier: 'SCARTI' }, { grade: 'GRADO I', tier: 'PENITENTI' }, { grade: 'GRADO II', tier: 'SCRIBI' },
    { grade: 'GRADO III', tier: 'SUDDITI' }, { grade: 'GRADO IV', tier: 'ARTEFICI' }, { grade: 'GRADO V', tier: 'INIZIATI' },
    { grade: 'GRADO VI', tier: 'CENTURIONI' }, { grade: 'GRADO VII', tier: 'PRETORIANI' }, { grade: 'GRADO VIII', tier: 'INQUISITORI' },
    { grade: 'GRADO IX', tier: 'MONARCHI' }
];

const LEVEL_NAMES = [
    "SPETTRO INERTE","LARVA CIECA","ECO SVUOTATA","CENERE UMIDA","MOLLUSCO SFATTO","PATINA DI SUDORE","RUGGINE VIVENTE","IMPRONTA SFOCATA","ANIMA VUOTA","TARLO DIURNO",
    "PENITENTE MUTO","FLAGELLATO","GENUFLESSO","PROSTRATO","SUPPLICE INDEGNO","RESPIRATORE","SERVO SILENTE","ZAVORRA UTILE","ATTREZZO ROTTO","RECLUTA GREZZA",
    "SCRIBA MEDIOCRE","NOTAIO DEL FALLIMENTO","TESTIMONE STANCO","VOCE OPACA","CRONISTA DEL VUOTO","DELATORE","ARCHIVISTA CARIE","AMANUENSE","CATALOGATORE D'OSSA","PORTAVOCE MUTO",
    "SUDDITO NECESSARIO","TRIBUTARIO","CENSITO","NUMERO REGISTRATO","SILICE VIVENTE","NUOVA MATRICOLA","GREGARIO ONESTO","VOTATO ALL'INUTILITÀ","OPEROSO SILENTE","PIETRA POSATA",
    "ARTIGIANO MINIMO","FABBRO DELLE ROUTINE","FALEGNAME DELL'INSONNIA","TESSITORE DI ORE","FONDITORE SOBRIO","INGRANAGGIO CROMATO","INCUDINE STOICA","FORGIATORE SILENTE","MURATORE D'ABITUDINI","GEOMETRA DEL TEMPO",
    "INIZIATO PROMETTENTE","NOVIZIO DEGNO","ADEPTO SILENTE","DISCIPULO VIGILE","PROSELITE ALFA","GUARDIA GIURATA","SENTINELLA","VEDETTA NOTTURNA","PORTATORE DI LAMPADA","VESSILLIFERO",
    "CENTURIONE MINORE","CAPORALE FERMO","LEGIONARIO VETERANO","DECURIONE","TRIBUNO","CENTURIONE DI FERRO","STANDARDIFERO","AQUILIFERO","PRIMIPILO","LEGATO DEL DOVERE",
    "PRETORIANO ALFA","GUARDIA IMPERIALE","VESSILLIFERO DELL'ORDINE","CATAFRATTO","PALADINO DEL RIGORE","TEMPLARE INTERNO","PARABELLIA","CROCIATO NEUTRO","ASSEDIATORE DELL'EGO","MARTELLO DI ADAMANTIO",
    "INQUISITORE MINORE","GIUDICE DELLA CARNE","CHIRURGO MORALE","CONFESSORE OSTILE","INQUISITORE MAGGIORE","GRAN INQUISITORE","VOCE DEL TRIBUNALE","MANO NERA","FLAGELLO DELLA MENZOGNA","ARCONTE DELLA GIUSTIZIA",
    "ARCONTE SILENTE","DOMINATORE INTERIORE","RE DI SE STESSO","MONARCA ASSOLUTO","IMPERATORE STOICO","CUSTODE DELL'ORDINE","ORACOLO DELLA LEGGE","SIGNORE DELL'ETERNO NO","QUASI-DIVINITÀ","OSIRIS INCARNATO"
];

const ACHIEVEMENTS = [
    { id: 'first_blood', title: 'PRIMO SANGUE', desc: 'Sopravvivi al primo giudizio.', icon: '🗡️' },
    { id: 'streak_7', title: 'DOGMA', desc: 'Mantieni una catena di 7 giorni perfetti.', icon: '⛓️' },
    { id: 'streak_30', title: 'MONOLITE', desc: 'Mantieni una catena di 30 giorni perfetti.', icon: '🕋' },
    { id: 'boss_mythic', title: 'DEICIDA', desc: 'Distruggi il Boss con un indice Mythic (≥90%).', icon: '👑' },
    { id: 'purgatory_escape', title: 'REDENZIONE', desc: 'Esci dalla modalità Purgatorio con un 100%.', icon: '🔥' },
    { id: 'level_50', title: 'MEZZO SECOLO', desc: 'Raggiungi il livello 50.', icon: '⏳' },
    { id: 'total_100_tasks', title: 'MACCHINA', desc: 'Completa 100 doveri totali.', icon: '⚙️' },
    { id: 'total_500_tasks', title: 'ALGORITMO', desc: 'Completa 500 doveri totali.', icon: '💻' },
    { id: 'prestige_1', title: 'ASCENSIONE', desc: 'Ottieni il tuo primo grado di Prestigio.', icon: '🌟' }
];

const TASK_SUGGESTIONS = [
    "BERE 2 LITRI D'ACQUA", "30 MINUTI DI LETTURA", "ALLENAMENTO FISICO 45 MIN", "NIENTE ZUCCHERI RAFFINATI",
    "MEDITAZIONE 10 MINUTI", "SCRIVI 3 OBIETTIVI DEL GIORNO", "NIENTE SOCIAL PRIMA DI MEZZOGIORNO", "DORMI ALMENO 8 ORE",
    "CAMMINA 8000 PASSI", "STUDIA 45 MINUTI", "DOCCIA FREDDA", "RIORDINA LO SPAZIO DI LAVORO",
    "STRETCHING MATTUTINO", "PIANIFICA IL DOMANI", "NESSUN CIBO SPAZZATURA", "SCRIVI UN DIARIO",
    "50 FLESSIONI", "IMPARA 10 PAROLE NUOVE", "CHIAMA UNA PERSONA CARA", "SPEGNI SCHERMI 1H PRIMA DI DORMIRE",
    "COLAZIONE PROTEICA", "RIVEDI LE FINANZE", "20 MINUTI DI SOLE", "NIENTE CAFFEINA DOPO LE 14",
    "ORDINA UNA STANZA", "LAVORO PROFONDO 90 MIN SENZA DISTRAZIONI", "RESPIRAZIONE 4-7-8", "PREPARA I VESTITI PER DOMANI",
    "SCRIVI 3 GRATITUDINI", "NIENTE LAMENTELE PER UN GIORNO", "100 SQUAT", "BEVI UN TÈ VERDE",
    "LEGGI 10 PAGINE DI SAGGISTICA", "DISATTIVA LE NOTIFICHE INUTILI", "CORSA 20 MINUTI", "MANGIA VERDURA A OGNI PASTO",
    "RIVEDI I TUOI OBIETTIVI MENSILI", "PULISCI LA CASELLA EMAIL", "10 MINUTI DI SILENZIO TOTALE", "STUDIA UN CAPITOLO",
    "ALLENA LA POSTURA", "NIENTE ALCOL OGGI", "SCRIVI PER 15 MINUTI", "AGGIORNA LA LISTA DELLE SPESE",
    "FAI IL LETTO APPENA SVEGLIO", "EVITA IL MULTITASKING", "RIPASSA GLI APPUNTI", "BEVI ACQUA APPENA SVEGLIO",
    "CAMMINATA SERALE", "PROGRAMMA UNA PAUSA VERA", "NIENTE TELEFONO A TAVOLA", "DEDICA 20 MIN A UN HOBBY",
    "PLANK 3 MINUTI TOTALI", "RIDUCI IL TEMPO SCHERMO DEL 20%", "SCRIVI UNA COSA DA MIGLIORARE", "ORGANIZZA I FILE DEL PC",
    "MANGIA LENTAMENTE E CONSAPEVOLE", "FAI QUALCOSA CHE RIMANDI DA GIORNI", "LEGGI PRIMA DI DORMIRE", "IDRATAZIONE COSTANTE"
];
